# Generated by Django 5.2.13 on 2026-05-01 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanciaPresentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej: "Planificaciones Anuales 2026"', max_length=200
                    ),
                ),
                (
                    "anio_academico",
                    models.PositiveSmallIntegerField(
                        help_text="Año académico (ej: 2026)"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("anual", "Anual"),
                            ("1cuat", "1° Cuatrimestre"),
                            ("2cuat", "2° Cuatrimestre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "solo_regimen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anual", "Anual"),
                            ("1cuat", "1° Cuatrimestre"),
                            ("2cuat", "2° Cuatrimestre"),
                        ],
                        help_text="Filtrar materias por régimen (vacío = todos)",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(help_text="Fecha desde la cual se aceptan envíos"),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        help_text="Fecha límite para envíos (después son tardíos)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("abierta", "Abierta"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="programada",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "carreras",
                    models.ManyToManyField(
                        help_text="Carreras incluidas en esta instancia",
                        related_name="instancias",
                        to="catalogos.carrera",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instancias_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filtrar por institución (vacío = todas)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.institucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "instancia de presentación",
                "verbose_name_plural": "instancias de presentación",
                "ordering": ["-anio_academico", "-fecha_apertura"],
            },
        ),
    ]
