# Generated by Django 5.2.13 on 2026-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instancias", "0002_instanciapresentacion_anios_cursado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instanciapresentacion",
            name="solo_regimen",
        ),
        migrations.AlterField(
            model_name="instanciapresentacion",
            name="periodo",
            field=models.CharField(
                choices=[
                    ("todos", "Todos los regímenes"),
                    ("anual", "Anual"),
                    ("1cuat", "1° Cuatrimestre"),
                    ("2cuat", "2° Cuatrimestre"),
                ],
                max_length=5,
            ),
        ),
    ]
