# Generated by Django 5.2.15 on 2026-06-24 15:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_carrera_modificado_por_institucion_fecha_creacion_and_more'),
        ('instancias', '0003_remove_solo_regimen_add_todos_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciapresentacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instanciapresentacion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.CreateModel(
            name='HistoricalInstanciaPresentacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('nombre', models.CharField(help_text='Ej: "Planificaciones Anuales 2026"', max_length=200)),
                ('anio_academico', models.PositiveSmallIntegerField(help_text='Año académico (ej: 2026)')),
                ('periodo', models.CharField(choices=[('todos', 'Todos los regímenes'), ('anual', 'Anual'), ('1cuat', '1° Cuatrimestre'), ('2cuat', '2° Cuatrimestre')], max_length=5)),
                ('anios_cursado', models.JSONField(blank=True, default=list, help_text='Años de cursado incluidos (lista de enteros, ej: [1,2,3]). Vacío = todos los años.')),
                ('fecha_apertura', models.DateField(help_text='Fecha desde la cual se aceptan envíos')),
                ('fecha_limite', models.DateField(help_text='Fecha límite para envíos (después son tardíos)')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='programada', max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(blank=True, db_constraint=False, help_text='Filtrar por institución (vacío = todas)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.institucion')),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'historical instancia de presentación',
                'verbose_name_plural': 'historical instancias de presentación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
