# Generated by Django 5.2.15 on 2026-06-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_historicaltipoplanificacion_tipoplanificacion'),
        ('instancias', '0004_instanciapresentacion_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanciapresentacion',
            name='tipo_planificacion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Define los campos obligatorios y la documentación para esta convocatoria.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.tipoplanificacion', verbose_name='tipo de planificación'),
        ),
        migrations.AddField(
            model_name='instanciapresentacion',
            name='tipo_planificacion',
            field=models.ForeignKey(blank=True, help_text='Define los campos obligatorios y la documentación para esta convocatoria.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='catalogos.tipoplanificacion', verbose_name='tipo de planificación'),
        ),
    ]
