# Generated by Django 5.2.15 on 2026-06-24 15:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_carrera_modificado_por_institucion_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTipoPlanificacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('campos_obligatorios', models.JSONField(default=list, help_text='Lista de claves de campos obligatorios a verificar en el documento Word.')),
                ('link_documentacion', models.URLField(blank=True, help_text='URL a guía o documentación adicional para este tipo.', verbose_name='link a documentación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'historical tipo de planificación',
                'verbose_name_plural': 'historical tipos de planificación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TipoPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('campos_obligatorios', models.JSONField(default=list, help_text='Lista de claves de campos obligatorios a verificar en el documento Word.')),
                ('link_documentacion', models.URLField(blank=True, help_text='URL a guía o documentación adicional para este tipo.', verbose_name='link a documentación')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'tipo de planificación',
                'verbose_name_plural': 'tipos de planificación',
                'ordering': ['titulo'],
            },
        ),
    ]
