# Generated by Django 5.2.13 on 2026-05-01 01:52

import apps.planificaciones.models
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0001_initial"),
        ("instancias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "instancia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="instancias.instanciapresentacion",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="catalogos.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones",
                        to="catalogos.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "planificación",
                "verbose_name_plural": "planificaciones",
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "archivo",
                    models.FileField(
                        upload_to=apps.planificaciones.models.version_path
                    ),
                ),
                (
                    "estado",
                    django_fsm.FSMField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("en_revision", "En Revisión"),
                            ("rechazada_auto", "Rechazada (Automático)"),
                            ("rechazada", "Rechazada"),
                            ("aprobada", "Aprobada"),
                            ("oficial", "Oficial Vigente"),
                            ("reemplazada", "Reemplazada"),
                        ],
                        default="borrador",
                        max_length=50,
                    ),
                ),
                ("entrega_tardia", models.BooleanField(default=False)),
                ("dias_atraso", models.PositiveSmallIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "campos_faltantes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de campos obligatorios faltantes",
                    ),
                ),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="planificaciones.planificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión",
                "verbose_name_plural": "versiones",
                "ordering": ["-numero"],
                "unique_together": {("planificacion", "numero")},
            },
        ),
        migrations.AddField(
            model_name="planificacion",
            name="version_oficial",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="es_oficial_de",
                to="planificaciones.version",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planificacion",
            unique_together={("materia", "profesor", "instancia")},
        ),
    ]
