# Generated by Django 5.2.13 on 2026-05-12 16:54

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="estado",
            field=django_fsm.FSMField(
                choices=[
                    ("borrador", "Borrador"),
                    ("en_revision", "En Revisión"),
                    ("rechazada_auto", "Rechazada (Automático)"),
                    ("rechazada", "Rechazada"),
                    ("aprobada", "Aprobada"),
                    ("oficial", "Oficial Vigente"),
                    ("reemplazada", "Reemplazada"),
                ],
                default="borrador",
                max_length=50,
            ),
        ),
    ]
