# Generated by Django 5.2.13 on 2026-05-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instancias", "0003_remove_solo_regimen_add_todos_periodo"),
        ("planificaciones", "0002_eliminar_estado_enviada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificacion",
            name="instancia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planificaciones",
                to="instancias.instanciapresentacion",
            ),
        ),
    ]
