# Generated by Django 5.2.13 on 2026-05-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tomar", "Tomar para revisión"),
                            ("aprobar", "Aprobar"),
                            ("rechazar", "Rechazar"),
                            ("correccion_leve", "Corrección leve"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones de rechazo o comentarios de aprobación",
                    ),
                ),
                (
                    "detalle_correccion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la corrección aplicada (para corrección leve)",
                    ),
                ),
                (
                    "archivo_corregido",
                    models.FileField(
                        blank=True,
                        help_text="Documento con la corrección leve (opcional)",
                        null=True,
                        upload_to="correcciones/",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones",
                        to="planificaciones.version",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisión",
                "verbose_name_plural": "revisiones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VistoBueno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        help_text="'moderadora' o 'coordinador'", max_length=20
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vistos_buenos",
                        to="planificaciones.version",
                    ),
                ),
            ],
            options={
                "verbose_name": "visto bueno",
                "verbose_name_plural": "vistos buenos",
                "unique_together": {("version", "rol")},
            },
        ),
    ]
