# Generated by Django 5.2.13 on 2026-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificaciones", "0001_initial"),
        ("revisiones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="planificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisiones",
                to="planificaciones.planificacion",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("tomar", "Revisión iniciada"),
                    ("aprobar", "Aprobar"),
                    ("rechazar", "Rechazar"),
                    ("correccion_leve", "Corrección leve"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="version",
            field=models.ForeignKey(
                blank=True,
                help_text="Versión específica a la que corresponde esta acción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisiones",
                to="planificaciones.version",
            ),
        ),
    ]
